#include <string>

#include "../../piece/Piece.h"
#include "../../position/Position.h"

/// @brief Interpretation of movement generated by the chess bot into an HTML format. 
class Message {
    public:
        // If the game was just created then we'll return a method that will not only 
        // give an okay result, but the isssued game id for the client for GET. 
        // If GET then just give the move that the computer made. 

        // For GET Messages
        Message(const Piece&, const Position&);
        // For POST Messages.
        Message(const int&);
        ~Message();
        std::string _get_as_string() const;
    private:
        const std::string _html_return_message; // Message sent to client. 
};