#include <string>

#include "../../piece/Piece.h"
#include "../../position/Position.h"

/// @brief Interpretation of movement generated by the chess bot into an HTML format. 
class Message {
// This class is used for conversion of the data returned by the engine -- which is in terms of data types of the 
// program -- in string form so it can be understood by the client. It works by returning FEN Chess Notation which can
// model any position on the board. It takes in FEN through Request and gives it back in a Message. 

    public:
        Message(const Piece&, const Position&, );
        ~Message();
        std::string _get() const;
    private:
        std::string MESSAGE; // Message that will be sent to client. 

        std::string _as_fen_notation(const Piece&, const Position&);
};